/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package concessionaria.view;

import concessionaria.controller.CarroController;
import javax.swing.JOptionPane;


public class TelaCadastroCarro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroCarro
     */
    public TelaCadastroCarro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jPanelCadastroCarro = new javax.swing.JPanel();
        jLabelChassiVenda = new javax.swing.JLabel();
        jLabelModeloCarro = new javax.swing.JLabel();
        jLabelCor = new javax.swing.JLabel();
        jLabelAno = new javax.swing.JLabel();
        jLabelPotencia = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldChassiCadastro1 = new javax.swing.JTextField();
        jTextFieldCor = new javax.swing.JTextField();
        jTextFieldAno = new javax.swing.JTextField();
        jTextFieldPotencia = new javax.swing.JTextField();
        jTextFieldValorCadastro = new javax.swing.JTextField();
        jButtonCadastrarCarro = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Esmeralda Veículos");
        setResizable(false);

        jLabelTitulo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelTitulo.setText("Cadastrar Carro");

        jPanelCadastroCarro.setBackground(new java.awt.Color(102, 102, 102));
        jPanelCadastroCarro.setPreferredSize(new java.awt.Dimension(780, 400));

        jLabelChassiVenda.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelChassiVenda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelChassiVenda.setText("Chassi:");

        jLabelModeloCarro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelModeloCarro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelModeloCarro.setText("Modelo:");

        jLabelCor.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelCor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCor.setText("Cor:");

        jLabelAno.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelAno.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAno.setText("Ano:");

        jLabelPotencia.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelPotencia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPotencia.setText("Potência:");

        jLabelValor.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelValor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValor.setText("Valor:");

        jTextFieldModelo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextFieldModelo.setToolTipText("Digite o modelo do carro");

        jTextFieldChassiCadastro1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextFieldChassiCadastro1.setToolTipText("Digite apenas os números");
        jTextFieldChassiCadastro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldChassiCadastro1ActionPerformed(evt);
            }
        });

        jTextFieldCor.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextFieldCor.setToolTipText("Digite a cor do carro");

        jTextFieldAno.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextFieldAno.setToolTipText("Digite apenas o ano final. 2012/2013. Digite 2013");

        jTextFieldPotencia.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextFieldPotencia.setToolTipText("Digite apenas numero. Valor em cv");

        jTextFieldValorCadastro.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextFieldValorCadastro.setToolTipText("Digite apenas numero. Sem ponto ou vírgula");

        jButtonCadastrarCarro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonCadastrarCarro.setText("Cadastrar");
        jButtonCadastrarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarCarro(evt);
            }
        });

        jButtonLimpar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparTela(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroCarroLayout = new javax.swing.GroupLayout(jPanelCadastroCarro);
        jPanelCadastroCarro.setLayout(jPanelCadastroCarroLayout);
        jPanelCadastroCarroLayout.setHorizontalGroup(
            jPanelCadastroCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroCarroLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelCadastroCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroCarroLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPotencia)
                            .addComponent(jLabelValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastroCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPotencia, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(jTextFieldValorCadastro)))
                    .addGroup(jPanelCadastroCarroLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelModeloCarro)
                            .addComponent(jLabelCor)
                            .addComponent(jLabelAno))
                        .addGroup(jPanelCadastroCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroCarroLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanelCadastroCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelCadastroCarroLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelCadastroCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldChassiCadastro1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                    .addComponent(jTextFieldModelo)))))
                    .addComponent(jLabelChassiVenda))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelCadastroCarroLayout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jButtonCadastrarCarro)
                .addGap(71, 71, 71)
                .addComponent(jButtonLimpar)
                .addGap(0, 244, Short.MAX_VALUE))
        );
        jPanelCadastroCarroLayout.setVerticalGroup(
            jPanelCadastroCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroCarroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelChassiVenda)
                    .addComponent(jTextFieldChassiCadastro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanelCadastroCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelModeloCarro)
                    .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCor)
                    .addComponent(jTextFieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelCadastroCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAno)
                    .addComponent(jTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanelCadastroCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPotencia)
                    .addComponent(jTextFieldPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelCadastroCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValor)
                    .addComponent(jTextFieldValorCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanelCadastroCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrarCarro)
                    .addComponent(jButtonLimpar))
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jLabelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelCadastroCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelCadastroCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldChassiCadastro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldChassiCadastro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldChassiCadastro1ActionPerformed

    private void cadastrarCarro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarCarro
        CarroController cc = new CarroController();
        if(jTextFieldAno.getText().equals("") || jTextFieldChassiCadastro1.getText().equals("")
                || jTextFieldCor.getText().equals("") || jTextFieldModelo.getText().equals("") 
                || jTextFieldPotencia.getText().equals("") || jTextFieldValorCadastro.getText().equals("")) {
           JOptionPane.showMessageDialog(null,"Algum campo vazio", "ERRO", JOptionPane.DEFAULT_OPTION);             
        } else {
            String nome = jTextFieldModelo.getText();
            int ano = Integer.parseInt(jTextFieldAno.getText());
            int chassi = Integer.parseInt(jTextFieldChassiCadastro1.getText());
            String cor = jTextFieldCor.getText();
            int potencia = Integer.parseInt(jTextFieldPotencia.getText());
            double valor = Double.parseDouble(jTextFieldValorCadastro.getText());
            
            cc.addCarro(nome, cor, chassi, potencia, ano, valor);
        }
    }//GEN-LAST:event_cadastrarCarro

    private void limparTela(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparTela
        jTextFieldAno.setText("");
        jTextFieldChassiCadastro1.setText("");
        jTextFieldCor.setText("");
        jTextFieldModelo.setText("");
        jTextFieldPotencia.setText("");
        jTextFieldValorCadastro.setText("");
    }//GEN-LAST:event_limparTela

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarCarro;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JLabel jLabelAno;
    private javax.swing.JLabel jLabelChassiVenda;
    private javax.swing.JLabel jLabelCor;
    private javax.swing.JLabel jLabelModeloCarro;
    private javax.swing.JLabel jLabelPotencia;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JPanel jPanelCadastroCarro;
    public javax.swing.JTextField jTextFieldAno;
    public javax.swing.JTextField jTextFieldChassiCadastro1;
    public javax.swing.JTextField jTextFieldCor;
    public javax.swing.JTextField jTextFieldModelo;
    public javax.swing.JTextField jTextFieldPotencia;
    public javax.swing.JTextField jTextFieldValorCadastro;
    // End of variables declaration//GEN-END:variables
}
