/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package concessionaria.view;

import concessionaria.controller.VendaController;
import javax.swing.JOptionPane;

public class TelaVenda extends javax.swing.JFrame {

    /**
     * Creates new form TelaHistoricoVenda
     */
    public TelaVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jPanelHistoricoVendas = new javax.swing.JPanel();
        jLabelCPFVenda = new javax.swing.JLabel();
        jTextFieldChassiVenda = new javax.swing.JTextField();
        jLabelChassiVenda = new javax.swing.JLabel();
        jTextFieldCPFVenda = new javax.swing.JTextField();
        jButtonVender = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Esmeralda Veículos");
        setResizable(false);

        jLabelTitulo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelTitulo.setText("Venda");

        jPanelHistoricoVendas.setBackground(new java.awt.Color(102, 102, 102));
        jPanelHistoricoVendas.setPreferredSize(new java.awt.Dimension(780, 400));

        jLabelCPFVenda.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelCPFVenda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCPFVenda.setText("CPF:");

        jTextFieldChassiVenda.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextFieldChassiVenda.setToolTipText("Digite apenas os números");

        jLabelChassiVenda.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelChassiVenda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelChassiVenda.setText("Chassi:");

        jTextFieldCPFVenda.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextFieldCPFVenda.setToolTipText("Digite apenas os números");

        jButtonVender.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonVender.setText("Vender");
        jButtonVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venderCarro(evt);
            }
        });

        jButtonLimpar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparTela(evt);
            }
        });

        javax.swing.GroupLayout jPanelHistoricoVendasLayout = new javax.swing.GroupLayout(jPanelHistoricoVendas);
        jPanelHistoricoVendas.setLayout(jPanelHistoricoVendasLayout);
        jPanelHistoricoVendasLayout.setHorizontalGroup(
            jPanelHistoricoVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistoricoVendasLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelHistoricoVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCPFVenda)
                    .addComponent(jLabelChassiVenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelHistoricoVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldChassiVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(jTextFieldCPFVenda))
                .addGap(564, 564, 564))
            .addGroup(jPanelHistoricoVendasLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jButtonVender)
                .addGap(122, 122, 122)
                .addComponent(jButtonLimpar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHistoricoVendasLayout.setVerticalGroup(
            jPanelHistoricoVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistoricoVendasLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanelHistoricoVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCPFVenda)
                    .addComponent(jTextFieldCPFVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanelHistoricoVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelChassiVenda)
                    .addComponent(jTextFieldChassiVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addGroup(jPanelHistoricoVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVender)
                    .addComponent(jButtonLimpar))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelHistoricoVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(jLabelTitulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelHistoricoVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void venderCarro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venderCarro
        VendaController vc = new VendaController();
        if(jTextFieldCPFVenda.getText().equals("") || jTextFieldChassiVenda.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Algum campo vazio", "ERRO", JOptionPane.DEFAULT_OPTION);    
        } else {
            String cpf = jTextFieldCPFVenda.getText();
            int chassi = Integer.parseInt(jTextFieldChassiVenda.getText());
            vc.realizarVenda(cpf, chassi);
        }
    }//GEN-LAST:event_venderCarro

    private void limparTela(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparTela
        jTextFieldCPFVenda.setText("");
        jTextFieldChassiVenda.setText("");
    }//GEN-LAST:event_limparTela

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonVender;
    private javax.swing.JLabel jLabelCPFVenda;
    private javax.swing.JLabel jLabelChassiVenda;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelHistoricoVendas;
    private javax.swing.JTextField jTextFieldCPFVenda;
    private javax.swing.JTextField jTextFieldChassiVenda;
    // End of variables declaration//GEN-END:variables
}
