/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package concessionaria.view;

import concessionaria.controller.CarroController;
import javax.swing.JOptionPane;


public class TelaAtualizarCarro extends javax.swing.JFrame {

    /**
     * Creates new form TelaAtualizarCarro
     */
    public TelaAtualizarCarro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jPanelAtualizarCarro = new javax.swing.JPanel();
        jLabelChassiAtualizar = new javax.swing.JLabel();
        jLabelModeloCarroAtualizar = new javax.swing.JLabel();
        jLabelCorAtualizar = new javax.swing.JLabel();
        jLabelAnoAtualizar = new javax.swing.JLabel();
        jLabelPotenciaAtualizar = new javax.swing.JLabel();
        jLabelValorAtualizar = new javax.swing.JLabel();
        jTextFieldChassiAtualizar = new javax.swing.JTextField();
        jTextFieldPotenciaAtualizar = new javax.swing.JTextField();
        jTextFieldValorAtualizar = new javax.swing.JTextField();
        jTextFieldAnoAtualizar = new javax.swing.JTextField();
        jTextFieldCorAtualizar = new javax.swing.JTextField();
        jTextFieldModeloAtualizar = new javax.swing.JTextField();
        jButtonAtualizarCarro = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Esmeralda Veículos");
        setResizable(false);

        jLabelTitulo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelTitulo.setText("Atualizar Carro");

        jPanelAtualizarCarro.setBackground(new java.awt.Color(102, 102, 102));
        jPanelAtualizarCarro.setPreferredSize(new java.awt.Dimension(780, 400));

        jLabelChassiAtualizar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelChassiAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelChassiAtualizar.setText("Chassi:");

        jLabelModeloCarroAtualizar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelModeloCarroAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelModeloCarroAtualizar.setText("Modelo:");

        jLabelCorAtualizar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelCorAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCorAtualizar.setText("Cor:");

        jLabelAnoAtualizar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelAnoAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAnoAtualizar.setText("Ano:");

        jLabelPotenciaAtualizar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelPotenciaAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPotenciaAtualizar.setText("Potência:");

        jLabelValorAtualizar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelValorAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValorAtualizar.setText("Valor:");

        jTextFieldChassiAtualizar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextFieldChassiAtualizar.setToolTipText("Digite apenas os números");
        jTextFieldChassiAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldChassiAtualizarActionPerformed(evt);
            }
        });

        jTextFieldPotenciaAtualizar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextFieldPotenciaAtualizar.setToolTipText("Digite apenas numero. Valor em cv");

        jTextFieldValorAtualizar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextFieldValorAtualizar.setToolTipText("Digite apenas numero. Sem ponto ou vírgula");

        jTextFieldAnoAtualizar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextFieldAnoAtualizar.setToolTipText("Digite apenas o ano final. 2012/2013. Digite 2013");

        jTextFieldCorAtualizar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextFieldCorAtualizar.setToolTipText("Digite a cor do carro");

        jTextFieldModeloAtualizar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextFieldModeloAtualizar.setToolTipText("Digite o modelo do carro");

        jButtonAtualizarCarro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonAtualizarCarro.setText("Atualizar");
        jButtonAtualizarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarCarro(evt);
            }
        });

        jButtonLimpar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonLimpar.setText("Limpar");

        javax.swing.GroupLayout jPanelAtualizarCarroLayout = new javax.swing.GroupLayout(jPanelAtualizarCarro);
        jPanelAtualizarCarro.setLayout(jPanelAtualizarCarroLayout);
        jPanelAtualizarCarroLayout.setHorizontalGroup(
            jPanelAtualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAtualizarCarroLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelAtualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPotenciaAtualizar)
                    .addComponent(jLabelValorAtualizar)
                    .addComponent(jLabelAnoAtualizar)
                    .addComponent(jLabelCorAtualizar)
                    .addComponent(jLabelModeloCarroAtualizar)
                    .addComponent(jLabelChassiAtualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAtualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAtualizarCarroLayout.createSequentialGroup()
                        .addComponent(jTextFieldChassiAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                        .addGap(359, 359, 359))
                    .addGroup(jPanelAtualizarCarroLayout.createSequentialGroup()
                        .addGroup(jPanelAtualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldModeloAtualizar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAnoAtualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCorAtualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelAtualizarCarroLayout.createSequentialGroup()
                        .addGroup(jPanelAtualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldValorAtualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(jTextFieldPotenciaAtualizar, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanelAtualizarCarroLayout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(jButtonAtualizarCarro)
                .addGap(54, 54, 54)
                .addComponent(jButtonLimpar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelAtualizarCarroLayout.setVerticalGroup(
            jPanelAtualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAtualizarCarroLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelAtualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelChassiAtualizar)
                    .addComponent(jTextFieldChassiAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanelAtualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelModeloCarroAtualizar)
                    .addComponent(jTextFieldModeloAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAtualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAtualizarCarroLayout.createSequentialGroup()
                        .addComponent(jLabelCorAtualizar)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAtualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAtualizarCarroLayout.createSequentialGroup()
                                .addComponent(jLabelAnoAtualizar)
                                .addGap(18, 18, 18)
                                .addGroup(jPanelAtualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelPotenciaAtualizar)
                                    .addComponent(jTextFieldPotenciaAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelAtualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelValorAtualizar)
                                    .addComponent(jTextFieldValorAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTextFieldAnoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextFieldCorAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanelAtualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAtualizarCarro)
                    .addComponent(jButtonLimpar))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelAtualizarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAtualizarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldChassiAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldChassiAtualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldChassiAtualizarActionPerformed

    private void atualizarCarro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarCarro
        CarroController cc = new CarroController();
        if(jTextFieldAnoAtualizar.getText().equals("") || jTextFieldChassiAtualizar.getText().equals("")
                || jTextFieldCorAtualizar.getText().equals("") || jTextFieldModeloAtualizar.getText().equals("") 
                || jTextFieldPotenciaAtualizar.getText().equals("") || jTextFieldValorAtualizar.getText().equals("")) {
           JOptionPane.showMessageDialog(null,"Algum campo vazio", "ERRO", JOptionPane.DEFAULT_OPTION);             
        } else {
            String nome = jTextFieldModeloAtualizar.getText();
            int ano = Integer.parseInt(jTextFieldAnoAtualizar.getText());
            int chassi = Integer.parseInt(jTextFieldChassiAtualizar.getText());
            String cor = jTextFieldCorAtualizar.getText();
            int potencia = Integer.parseInt(jTextFieldPotenciaAtualizar.getText());
            double valor = Double.parseDouble(jTextFieldValorAtualizar.getText());
            
            cc.atualizarCarro(nome, cor, chassi, potencia, ano, valor);
        }
            
    }//GEN-LAST:event_atualizarCarro

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtualizarCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizarCarro;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JLabel jLabelAnoAtualizar;
    private javax.swing.JLabel jLabelChassiAtualizar;
    private javax.swing.JLabel jLabelCorAtualizar;
    private javax.swing.JLabel jLabelModeloCarroAtualizar;
    private javax.swing.JLabel jLabelPotenciaAtualizar;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelValorAtualizar;
    private javax.swing.JPanel jPanelAtualizarCarro;
    private javax.swing.JTextField jTextFieldAnoAtualizar;
    private javax.swing.JTextField jTextFieldChassiAtualizar;
    private javax.swing.JTextField jTextFieldCorAtualizar;
    private javax.swing.JTextField jTextFieldModeloAtualizar;
    private javax.swing.JTextField jTextFieldPotenciaAtualizar;
    private javax.swing.JTextField jTextFieldValorAtualizar;
    // End of variables declaration//GEN-END:variables
}
