/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package concessionaria.view;


public class TelaPrincipal extends javax.swing.JFrame {

    /** Creates new form TelaPrincipal */
    public TelaPrincipal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTelaPrincipal = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jMenuBarTelaPrincipal = new javax.swing.JMenuBar();
        jMenuCliente = new javax.swing.JMenu();
        jMenuItemAdicionar = new javax.swing.JMenuItem();
        jMenuItemRemover = new javax.swing.JMenuItem();
        jMenuItemAtualizar = new javax.swing.JMenuItem();
        jMenuItemListarCliente = new javax.swing.JMenuItem();
        jMenuCarro = new javax.swing.JMenu();
        jMenuItemAdicionarCarro = new javax.swing.JMenuItem();
        jMenuItemRemoverCarro = new javax.swing.JMenuItem();
        jMenuItemAtualizarCarro = new javax.swing.JMenuItem();
        jMenuItemListarCarro = new javax.swing.JMenuItem();
        jMenuVenda = new javax.swing.JMenu();
        jMenuItemRealizarVenda = new javax.swing.JMenuItem();
        jMenuItemHistoricoVenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Esmeralda Veículos");
        setResizable(false);

        jPanelTelaPrincipal.setBackground(new java.awt.Color(150, 150, 150));
        jPanelTelaPrincipal.setPreferredSize(new java.awt.Dimension(780, 400));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/carro.png"))); // NOI18N

        org.jdesktop.layout.GroupLayout jPanelTelaPrincipalLayout = new org.jdesktop.layout.GroupLayout(jPanelTelaPrincipal);
        jPanelTelaPrincipal.setLayout(jPanelTelaPrincipalLayout);
        jPanelTelaPrincipalLayout.setHorizontalGroup(
            jPanelTelaPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelTelaPrincipalLayout.createSequentialGroup()
                .add(jLabelLogo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 770, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTelaPrincipalLayout.setVerticalGroup(
            jPanelTelaPrincipalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelTelaPrincipalLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabelLogo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 600, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuCliente.setText("Cliente");
        jMenuCliente.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jMenuItemAdicionar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuItemAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seta.png"))); // NOI18N
        jMenuItemAdicionar.setText("Adicionar");
        jMenuItemAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirTelaCadastroCliente(evt);
            }
        });
        jMenuCliente.add(jMenuItemAdicionar);

        jMenuItemRemover.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuItemRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seta.png"))); // NOI18N
        jMenuItemRemover.setText("Remover");
        jMenuItemRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirTelaRemoverCliente(evt);
            }
        });
        jMenuCliente.add(jMenuItemRemover);

        jMenuItemAtualizar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuItemAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seta.png"))); // NOI18N
        jMenuItemAtualizar.setText("Atualizar");
        jMenuItemAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirTelaAtualizarCliente(evt);
            }
        });
        jMenuCliente.add(jMenuItemAtualizar);

        jMenuItemListarCliente.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuItemListarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seta.png"))); // NOI18N
        jMenuItemListarCliente.setText("Listar");
        jMenuItemListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirTelaListarClientes(evt);
            }
        });
        jMenuCliente.add(jMenuItemListarCliente);

        jMenuBarTelaPrincipal.add(jMenuCliente);

        jMenuCarro.setText("Carro");
        jMenuCarro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jMenuItemAdicionarCarro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuItemAdicionarCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seta.png"))); // NOI18N
        jMenuItemAdicionarCarro.setText("Adicionar");
        jMenuItemAdicionarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirTelaCadastroCarro(evt);
            }
        });
        jMenuCarro.add(jMenuItemAdicionarCarro);

        jMenuItemRemoverCarro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuItemRemoverCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seta.png"))); // NOI18N
        jMenuItemRemoverCarro.setText("Remover");
        jMenuItemRemoverCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirTelaRemoverCarro(evt);
            }
        });
        jMenuCarro.add(jMenuItemRemoverCarro);

        jMenuItemAtualizarCarro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuItemAtualizarCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seta.png"))); // NOI18N
        jMenuItemAtualizarCarro.setText("Atualizar");
        jMenuItemAtualizarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirTelaAtualizarCarro(evt);
            }
        });
        jMenuCarro.add(jMenuItemAtualizarCarro);

        jMenuItemListarCarro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuItemListarCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seta.png"))); // NOI18N
        jMenuItemListarCarro.setText("Listar");
        jMenuItemListarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirTelaListagemCarros(evt);
            }
        });
        jMenuCarro.add(jMenuItemListarCarro);

        jMenuBarTelaPrincipal.add(jMenuCarro);

        jMenuVenda.setText("Venda");
        jMenuVenda.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirTelaListagemVendas(evt);
            }
        });

        jMenuItemRealizarVenda.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuItemRealizarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seta.png"))); // NOI18N
        jMenuItemRealizarVenda.setText("Realizar Venda");
        jMenuItemRealizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirTelaVenda(evt);
            }
        });
        jMenuVenda.add(jMenuItemRealizarVenda);

        jMenuItemHistoricoVenda.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuItemHistoricoVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seta.png"))); // NOI18N
        jMenuItemHistoricoVenda.setText("Listar Vendas");
        jMenuVenda.add(jMenuItemHistoricoVenda);

        jMenuBarTelaPrincipal.add(jMenuVenda);

        setJMenuBar(jMenuBarTelaPrincipal);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .add(jPanelTelaPrincipal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(74, 74, 74)
                .add(jPanelTelaPrincipal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void abrirTelaCadastroCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirTelaCadastroCliente
       new TelaCadastroCliente().setVisible(true);       
    }//GEN-LAST:event_abrirTelaCadastroCliente

    private void AbrirTelaRemoverCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirTelaRemoverCliente
        new TelaRemoverCliente().setVisible(true);
    }//GEN-LAST:event_AbrirTelaRemoverCliente

    private void abrirTelaAtualizarCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirTelaAtualizarCliente
        new TelaAtualizarCliente().setVisible(true);
    }//GEN-LAST:event_abrirTelaAtualizarCliente

    private void abrirTelaCadastroCarro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirTelaCadastroCarro
        new TelaCadastroCarro().setVisible(true);
    }//GEN-LAST:event_abrirTelaCadastroCarro

    private void abrirTelaRemoverCarro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirTelaRemoverCarro
        new TelaRemoverCarro().setVisible(true);
    }//GEN-LAST:event_abrirTelaRemoverCarro

    private void abrirTelaAtualizarCarro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirTelaAtualizarCarro
        new TelaAtualizarCarro().setVisible(true);
    }//GEN-LAST:event_abrirTelaAtualizarCarro

    private void abrirTelaVenda(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirTelaVenda
        new TelaVenda().setVisible(true);
    }//GEN-LAST:event_abrirTelaVenda

    private void abrirTelaListarClientes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirTelaListarClientes
        new TelaMostrarClientes().setVisible(true);
    }//GEN-LAST:event_abrirTelaListarClientes

    private void abrirTelaListagemCarros(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirTelaListagemCarros
        new TelaMostrarCarros().setVisible(true);
    }//GEN-LAST:event_abrirTelaListagemCarros

    private void abrirTelaListagemVendas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirTelaListagemVendas
        new TelaMostrarVendas().setVisible(true);
    }//GEN-LAST:event_abrirTelaListagemVendas

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JMenuBar jMenuBarTelaPrincipal;
    private javax.swing.JMenu jMenuCarro;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenuItem jMenuItemAdicionar;
    private javax.swing.JMenuItem jMenuItemAdicionarCarro;
    private javax.swing.JMenuItem jMenuItemAtualizar;
    private javax.swing.JMenuItem jMenuItemAtualizarCarro;
    private javax.swing.JMenuItem jMenuItemHistoricoVenda;
    private javax.swing.JMenuItem jMenuItemListarCarro;
    private javax.swing.JMenuItem jMenuItemListarCliente;
    private javax.swing.JMenuItem jMenuItemRealizarVenda;
    private javax.swing.JMenuItem jMenuItemRemover;
    private javax.swing.JMenuItem jMenuItemRemoverCarro;
    private javax.swing.JMenu jMenuVenda;
    private javax.swing.JPanel jPanelTelaPrincipal;
    // End of variables declaration//GEN-END:variables

}
