/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package concessionaria.view;

import concessionaria.controller.ClienteController;
import javax.swing.JOptionPane;


public class TelaAtualizarCliente extends javax.swing.JFrame {

    /** Creates new form TelaAtualizarCliente */
    public TelaAtualizarCliente() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jPanelAtualizarCliente = new javax.swing.JPanel();
        jLabelCPFAtualizarCliente = new javax.swing.JLabel();
        jLabelNomeAtualizar = new javax.swing.JLabel();
        jLabelIdadeAtualizar = new javax.swing.JLabel();
        jTextFieldCPF = new javax.swing.JTextField();
        jTextFieldNomeAtualizar = new javax.swing.JTextField();
        jTextFieldIdadeAtualizar = new javax.swing.JTextField();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Esmeralda Veículos");
        setResizable(false);

        jLabelTitulo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelTitulo.setText("Atualizar Cliente");

        jPanelAtualizarCliente.setBackground(new java.awt.Color(102, 102, 102));
        jPanelAtualizarCliente.setPreferredSize(new java.awt.Dimension(780, 400));

        jLabelCPFAtualizarCliente.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelCPFAtualizarCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCPFAtualizarCliente.setText("CPF:");

        jLabelNomeAtualizar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelNomeAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeAtualizar.setText("Nome:");

        jLabelIdadeAtualizar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelIdadeAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIdadeAtualizar.setText("Idade:");
        jLabelIdadeAtualizar.setToolTipText("");

        jTextFieldCPF.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextFieldCPF.setToolTipText("Digite apenas os números");

        jTextFieldNomeAtualizar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextFieldNomeAtualizar.setToolTipText("Nome do cliente");

        jTextFieldIdadeAtualizar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextFieldIdadeAtualizar.setToolTipText("Digite a idade do Cliente");

        jButtonAtualizar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarCliente(evt);
            }
        });

        jButtonLimpar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelAtualizarClienteLayout = new org.jdesktop.layout.GroupLayout(jPanelAtualizarCliente);
        jPanelAtualizarCliente.setLayout(jPanelAtualizarClienteLayout);
        jPanelAtualizarClienteLayout.setHorizontalGroup(
            jPanelAtualizarClienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelAtualizarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelAtualizarClienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabelIdadeAtualizar)
                    .add(jPanelAtualizarClienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanelAtualizarClienteLayout.createSequentialGroup()
                            .add(2, 2, 2)
                            .add(jLabelCPFAtualizarCliente))
                        .add(jLabelNomeAtualizar)))
                .add(18, 18, 18)
                .add(jPanelAtualizarClienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelAtualizarClienteLayout.createSequentialGroup()
                        .add(jTextFieldCPF, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                        .add(559, 559, 559))
                    .add(jPanelAtualizarClienteLayout.createSequentialGroup()
                        .add(jPanelAtualizarClienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTextFieldNomeAtualizar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 678, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextFieldIdadeAtualizar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .add(jPanelAtualizarClienteLayout.createSequentialGroup()
                .add(217, 217, 217)
                .add(jButtonAtualizar)
                .add(82, 82, 82)
                .add(jButtonLimpar)
                .add(0, 0, Short.MAX_VALUE))
        );
        jPanelAtualizarClienteLayout.setVerticalGroup(
            jPanelAtualizarClienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelAtualizarClienteLayout.createSequentialGroup()
                .add(56, 56, 56)
                .add(jPanelAtualizarClienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelCPFAtualizarCliente)
                    .add(jTextFieldCPF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(49, 49, 49)
                .add(jPanelAtualizarClienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelNomeAtualizar)
                    .add(jTextFieldNomeAtualizar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(49, 49, 49)
                .add(jPanelAtualizarClienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelIdadeAtualizar)
                    .add(jTextFieldIdadeAtualizar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 53, Short.MAX_VALUE)
                .add(jPanelAtualizarClienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonAtualizar)
                    .add(jButtonLimpar))
                .add(91, 91, 91))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabelTitulo)
                .add(312, 312, 312))
            .add(layout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jPanelAtualizarCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jLabelTitulo)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelAtualizarCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarCliente
        ClienteController cc = new ClienteController();
        if(jTextFieldNomeAtualizar.getText().equals("") || jTextFieldCPF.getText().equals("") 
                || jTextFieldIdadeAtualizar.getText().equals("") ){
            JOptionPane.showMessageDialog(null,"Algum campo vazio", "ERRO", JOptionPane.DEFAULT_OPTION);
        } else {
            String nome = jTextFieldNomeAtualizar.getText();
            String cpf = jTextFieldCPF.getText();            
            int idade = Integer.parseInt(jTextFieldIdadeAtualizar.getText());
            cc.atualizarCliente(cpf, nome, idade);
        }
    }//GEN-LAST:event_atualizarCliente

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jTextFieldNomeAtualizar.setText("");
        jTextFieldCPF.setText("");
        jTextFieldIdadeAtualizar.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtualizarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JLabel jLabelCPFAtualizarCliente;
    private javax.swing.JLabel jLabelIdadeAtualizar;
    private javax.swing.JLabel jLabelNomeAtualizar;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelAtualizarCliente;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldIdadeAtualizar;
    private javax.swing.JTextField jTextFieldNomeAtualizar;
    // End of variables declaration//GEN-END:variables

}
